/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    projects: Project;
    testimonials: Testimonial;
    'process-steps': ProcessStep;
    faqs: Faq;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'process-steps': ProcessStepsSelect<false> | ProcessStepsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'about-page': AboutPage;
    'contact-settings': ContactSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * One page for each thing you do. Click a service to change its photos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * The big photo at the top of the page, and on the home page card.
   */
  hero: number | Media;
  /**
   * Your work for this service. Drag to reorder — the first one shows largest. These also fill the Work page automatically.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Example: Modular Kitchen
   */
  name: string;
  navLabel: string;
  tagline: string;
  summary: string;
  /**
   * Optional. Example: Service 02
   */
  kicker?: string | null;
  slug: string;
  introHeading: string;
  introBody: {
    text: string;
    id?: string | null;
  }[];
  highlights?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  offerings?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  materials?:
    | {
        name: string;
        note: string;
        id?: string | null;
      }[]
    | null;
  priceNote?: string | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first. 1 shows at the top.
   */
  order: number;
  /**
   * Untick to hide this from the website without deleting it.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Helps you show up on Google. Leave blank if you are in a hurry — we fill it in for you.
   */
  alt?: string | null;
  isPlaceholder?: boolean | null;
  credit?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Jobs you have finished. These appear on the home page and the Work page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * For example: Stepped Ceiling, Whitefield
   */
  title: string;
  cover: number | Media;
  /**
   * For example: 3 BHK · Whitefield
   */
  locationLabel: string;
  year: string;
  /**
   * One or two lines about what you did.
   */
  caption: string;
  /**
   * Optional. Which of your services this job involved.
   */
  services?: (number | Service)[] | null;
  layout: 'wide' | 'standard';
  slug: string;
  /**
   * Lower numbers appear first. 1 shows at the top.
   */
  order: number;
  /**
   * Untick to hide this from the website without deleting it.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Copy the exact words from your Google reviews here. Please do not write reviews yourself — it is against the law to show made-up reviews.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Paste their exact words from Google.
   */
  quote: string;
  author: string;
  /**
   * For example: 3 BHK · Whitefield
   */
  context?: string | null;
  /**
   * A number from 1 to 5.
   */
  rating: number;
  /**
   * Usually the first letter of their name. Leave blank to do it automatically.
   */
  initial?: string | null;
  source?: string | null;
  /**
   * A warning shows on your website while this is ticked. Untick once you have pasted a genuine review.
   */
  isPlaceholder?: boolean | null;
  /**
   * Lower numbers appear first. 1 shows at the top.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * The steps shown under "How we work" on your home and service pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps".
 */
export interface ProcessStep {
  id: number;
  /**
   * For example: 01
   */
  numeral: string;
  title: string;
  body: string;
  /**
   * For example: Free, or Warranty
   */
  meta?: string | null;
  /**
   * Lower numbers appear first. 1 shows at the top.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions customers ask, shown on your home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Lower numbers appear first. 1 shows at the top.
   */
  order: number;
  /**
   * Untick to hide this from the website without deleting it.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can log in and edit this website. To change your own password, click your name in the top-right corner and choose Account.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'process-steps';
        value: number | ProcessStep;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  hero?: T;
  gallery?: T;
  name?: T;
  navLabel?: T;
  tagline?: T;
  summary?: T;
  kicker?: T;
  slug?: T;
  introHeading?: T;
  introBody?:
    | T
    | {
        text?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  offerings?:
    | T
    | {
        label?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        name?: T;
        note?: T;
        id?: T;
      };
  priceNote?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  cover?: T;
  locationLabel?: T;
  year?: T;
  caption?: T;
  services?: T;
  layout?: T;
  slug?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  context?: T;
  rating?: T;
  initial?: T;
  source?: T;
  isPlaceholder?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps_select".
 */
export interface ProcessStepsSelect<T extends boolean = true> {
  numeral?: T;
  title?: T;
  body?: T;
  meta?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  isPlaceholder?: T;
  credit?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The first page people see. Change the big photo, the headline and your numbers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Click it, choose one of your photos, press Save.
   */
  heroImage: number | Media;
  heroLine1: string;
  /**
   * Put *stars* around a word to make it gold. Example: with *light.*
   */
  heroLine2: string;
  heroSub: string;
  signatureImage: number | Media;
  /**
   * Put *stars* around a word to make it gold.
   */
  signatureQuote: string;
  rating: number;
  reviewCount: number;
  /**
   * Just the number. Shows as "10+ years".
   */
  yearsActive: string;
  /**
   * Just the number. Shows as "450+".
   */
  projectsDelivered: string;
  studioLead: string;
  reviews?:
    | {
        quote: string;
        author: string;
        /**
         * Example: 3 BHK, Whitefield
         */
        context?: string | null;
        rating: number;
        /**
         * A warning shows on your website while this is ticked.
         */
        isPlaceholder?: boolean | null;
        id?: string | null;
      }[]
    | null;
  questions?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  businessName: string;
  shortName: string;
  wordmarkLead: string;
  wordmarkRest: string;
  city: string;
  state: string;
  metaDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The page that tells customers who you are.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  /**
   * Put *stars* around a word to make it gold.
   */
  heading: string;
  image: number | Media;
  paragraphs: {
    text: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Your phone number, WhatsApp, address and the areas you cover.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  /**
   * How it looks on the website. Example: 099864 36139
   */
  phoneDisplay: string;
  /**
   * Must start with +91. Example: +919986436139
   */
  phoneE164: string;
  email: string;
  hours: string;
  /**
   * Open your business on Google Maps, press Share, paste the link.
   */
  googleMapsUrl: string;
  addressLines?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Helps people in those areas find you on Google.
   */
  serviceAreas?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroImage?: T;
  heroLine1?: T;
  heroLine2?: T;
  heroSub?: T;
  signatureImage?: T;
  signatureQuote?: T;
  rating?: T;
  reviewCount?: T;
  yearsActive?: T;
  projectsDelivered?: T;
  studioLead?: T;
  reviews?:
    | T
    | {
        quote?: T;
        author?: T;
        context?: T;
        rating?: T;
        isPlaceholder?: T;
        id?: T;
      };
  questions?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  businessName?: T;
  shortName?: T;
  wordmarkLead?: T;
  wordmarkRest?: T;
  city?: T;
  state?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heading?: T;
  image?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  phoneDisplay?: T;
  phoneE164?: T;
  email?: T;
  hours?: T;
  googleMapsUrl?: T;
  addressLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  serviceAreas?:
    | T
    | {
        area?: T;
        id?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}